### ISSUE TITLE
LastNotificationRead Date causes exception

### ISSUE THREAD

**Issue by mjlamb** [lapulpeta/Nostrid#82] opened 2023-02-15 22:20 UTC
I created a new account for testing.
When this line ran, 

        mentionsFilter.LimitFilterData.Since = accountService.MainAccount.LastNotificationRead;

line 567 in FeedService.cs, throw an exception, as it is invalid date range.

The date was in format of 0001-01-01 00:00:00
Looking into the db and column LastNotificationRead, all set to 0001-01-01 00:00:00

Adding a value date 2023-01-01 00:00:00 in the column allow the code to function.

**Comment by mjlamb** [comment] 2023-02-15 22:22
Exception
System.ArgumentOutOfRangeException: 'The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')'

**Comment by lapulpeta** [comment] 2023-02-16 10:28
It must be something related to the `DateTime` default value. I can't reproduce it but I suspect it might be related to the timezone. What is your timezone?

**Comment by mjlamb** [comment] 2023-02-16 10:30
I'm in NZ so UTC+13, but yes the default date values were as above... 0001-01-01 00:00:00  which are invalid.

**Comment by lapulpeta** [comment] 2023-02-16 10:48
Can you add `.ToUniversalTime()` at the end and try it again? Like this:

`mentionsFilter.LimitFilterData.Since = accountService.MainAccount.LastNotificationRead.ToUniversalTime();`

**Comment by mjlamb** [comment] 2023-02-16 19:11
Fixed in....
https://github.com/lapulpeta/Nostrid/pull/85

**Comment by lapulpeta** [comment] 2023-02-16 19:41
Merged. Thanks!

**Closed** 2023-02-16 19:40 UTC
